# Generated by Django 3.1.7 on 2021-11-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=60, unique=True, verbose_name='Телефон')),
                ('date_of_meeting', models.CharField(choices=[('Выбрать дату', 'Выбрать дату'), ('01', '01-01-2001'), ('02', '02-02-2002'), ('03', '03-03-2003')], default='Выбрать дату', max_length=50)),
                ('language', models.ForeignKey(default='ru', on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
        ),
    ]
