# Generated by Django 3.1.7 on 2021-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ua', 'Український')], default='ru', max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=60, unique=True, verbose_name='Телефон')),
                ('date_of_meeting', models.CharField(choices=[('Выбрать дату', 'Выбрать дату'), ('20', '20-11-2021'), ('30', '30-11-2021'), ('10', '10-12-2021')], default='Выбрать дату', max_length=50)),
            ],
        ),
    ]
