# Generated by Django 3.1.7 on 2021-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_meeting',
            field=models.CharField(choices=[('20', '20-11-2021'), ('30', '30-11-2021'), ('10', '10-12-2021')], default='20', max_length=50),
        ),
    ]
